name: CI/CD Pipeline

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2Ô∏è‚É£ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3Ô∏è‚É£ Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: docker build -t devsecure-api .

      # 4aÔ∏è‚É£ Debug: list Docker images
      - name: List local Docker images
        run: docker images

      # 5Ô∏è‚É£ Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "devsecure-api"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"

      # 6Ô∏è‚É£ Run Snyk Scan
      - name: Run Snyk Scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: devsecure-api:latest
          args: --file=Dockerfile --json-file-output=snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 7Ô∏è‚É£ Convert Snyk JSON report to HTML
      - name: Install snyk-to-html
        run: npm install -g snyk-to-html

      - name: Generate HTML report
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.html

      # 8Ô∏è‚É£ Scan for secrets with Gitleaks
      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 9Ô∏è‚É£ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # üîü Tag and push Docker image
      - name: Push image to Docker Hub
        run: |
          echo "Tagging image..."
          docker tag devsecure-api:latest ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest
          echo "Pushing image..."
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecure-api:latest